#!/usr/bin/env python3
"""マルコフ FX：シンボル連続最適化ランナー（詳細設計書 14.2 / 層②）

シンボルリストをループし、各シンボル用のテスター設定 .ini を生成して
MT5 ターミナルをヘッドレス起動 → 最適化を順番に実行する。
ユーザーはこのスクリプトを 1 回起動するだけでよい（手動のシンボル切替不要）。

各パスの結果は EA 側（OnTesterPass）から SQLite DB に記録されるため、
本ランナーはあくまで「最適化を順番に走らせる」役割に徹する。

使い方:
    python run_optimization.py --config config.example.json
"""
import argparse
import json
import subprocess
import sys
import tempfile
import time
from pathlib import Path


INI_TEMPLATE = """; auto-generated by run_optimization.py
[Tester]
Expert={expert}
Symbol={symbol}
Period={period}
Optimization={optimization}
Model={model}
FromDate={from_date}
ToDate={to_date}
ForwardMode={forward_mode}
Deposit={deposit}
Currency={currency}
Leverage={leverage}
ExecutionMode=0
OptimizationCriterion={criterion}
ShutdownTerminal=1
Report={report}
ReplaceReport=1
{inputs}
"""


def build_inputs(inputs: dict) -> str:
    """最適化レンジを .ini の `key=start||min||step||max||Y/N` 形式へ変換。

    値が dict（start/step/stop/optimize）なら最適化対象、スカラなら固定値。
    """
    lines = []
    for key, spec in inputs.items():
        if isinstance(spec, dict):
            start = spec.get("start")
            step = spec.get("step", 1)
            stop = spec.get("stop")
            opt = "Y" if spec.get("optimize", True) else "N"
            lines.append(f"{key}={start}||{start}||{step}||{stop}||{opt}")
        else:
            lines.append(f"{key}={spec}||{spec}||0||{spec}||N")
    return "\n".join(lines)


def make_ini(symbol: str, cfg: dict, out_dir: Path) -> Path:
    content = INI_TEMPLATE.format(
        expert=cfg["expert"],
        symbol=symbol,
        period=cfg.get("period", "D1"),
        optimization=cfg.get("optimization", 2),   # 2=遺伝的
        model=cfg.get("model", 1),                  # 1=1分足OHLC, 0=全ティック
        from_date=cfg["from_date"],
        to_date=cfg["to_date"],
        forward_mode=cfg.get("forward_mode", 0),
        deposit=cfg.get("deposit", 10000),
        currency=cfg.get("currency", "USD"),
        leverage=cfg.get("leverage", 100),
        criterion=cfg.get("criterion", 6),          # 6=カスタム(OnTester)
        report=f"report_{symbol}",
        inputs=build_inputs(cfg.get("inputs", {})),
    )
    ini_path = out_dir / f"{symbol}.ini"
    ini_path.write_text(content, encoding="utf-16")  # MT5 の .ini は UTF-16
    return ini_path


def run_symbol(terminal: str, ini_path: Path, timeout: int) -> int:
    """1 シンボルの最適化を実行（端末は ShutdownTerminal=1 で自動終了）。"""
    cmd = [terminal, f"/config:{ini_path}", "/portable"]
    print(f"[run] {ini_path.stem}: {' '.join(cmd)}", flush=True)
    start = time.time()
    proc = subprocess.run(cmd, timeout=timeout)
    print(f"[done] {ini_path.stem}: rc={proc.returncode} ({time.time()-start:.0f}s)", flush=True)
    return proc.returncode


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True, help="JSON 設定ファイル")
    ap.add_argument("--keep-ini", action="store_true", help="生成した .ini を残す")
    args = ap.parse_args()

    cfg = json.loads(Path(args.config).read_text(encoding="utf-8"))
    terminal = cfg["terminal_path"]
    symbols = cfg["symbols"]
    timeout = cfg.get("timeout_sec", 3600)

    out_dir = Path(cfg.get("ini_dir", tempfile.mkdtemp(prefix="markov_ini_")))
    out_dir.mkdir(parents=True, exist_ok=True)

    rc_total = 0
    for sym in symbols:
        ini_path = make_ini(sym, cfg, out_dir)
        try:
            rc = run_symbol(terminal, ini_path, timeout)
            rc_total |= rc
        except subprocess.TimeoutExpired:
            print(f"[timeout] {sym}", file=sys.stderr, flush=True)
            rc_total |= 1
        finally:
            if not args.keep_ini:
                ini_path.unlink(missing_ok=True)

    print("[all done] 全シンボルの最適化が完了しました。結果は SQLite DB を参照。")
    return rc_total


if __name__ == "__main__":
    raise SystemExit(main())
